#H2
spring:
  datasource:
    url: jdbc:h2:mem:person
    driver-class-name: org.h2.Driver
    username: sa
    password:
#Settings
  h2:
    console:
     enabled: true
     path: /h2-console
     settings:
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        ddl-auto: none